---

- name: Ensure required dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add apt key 
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install beats packages (YUM)
  apt:
    name: '{{ item }}'
    state: present
  loop: '{{ iserver_beats }}'

- name: Create PID Directory
  file:
    path: '/var/run'
    state: directory

- name: Create Config Directory
  file:
    path: '/etc/{{ item }}'
    state: directory
  loop: '{{ iserver_beats }}'

- name: Setup environment file
  template:
    src: beat.env.j2
    dest: '/etc/default/beats.env'
    mode: 0644
    owner: root
    group: root

- name: Update unit files
  copy:
    src: '{{ item }}.service'
    dest: '/lib/systemd/system/{{ item }}.service'
    mode: 0644
    owner: root
    group: root
  loop: '{{ iserver_beats }}'

- name: Copy config files
  copy:
    src: '{{ item }}'
    dest: '/etc/{{ item }}'
    mode: 0644
    owner: root
    group: root
  loop:
    - metricbeat/metricbeat.yml
    - metricbeat/modules.d/linux.yml
    - metricbeat/modules.d/system.yml
    - filebeat/filebeat.yml

- name: Start {{ beat }} service
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop: '{{ iserver_beats }}'
