# GROW PARTITION
# Debian, Ubuntu

- name: Ensure that cloud-guest-utils including growpart is installed.
  apt:
    name: cloud-guest-utils
    state: present

- name: Copy systemd unitfile to automatically Grow Partition after resize by Proxmox.
  copy:
    src: autogrowpart-debian-ubuntu.service
    dest: /etc/systemd/system/autogrowpart.service
    mode: 0644
  register: enable_autogrowpart

- name: Copy script to automatically Grow Partition after resize by Proxmox.
  template:
    src: auto_grow_partition-debian-ubuntu.sh.j2
    dest: /usr/local/bin/auto_grow_partition.sh
    mode: a+x

- name: Enable the autogrowpart service.
  service:
    name: autogrowpart
    enabled: yes
  when: enable_autogrowpart is changed
